install @xray-app/playwright-junit-reporter and change reporter in pl.config.js + new pl.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -32,23 +32,24 @@ jobs:
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
 
-      - name: Create report directory
-        run: mkdir -p playwright-report
-
       - name: Run Playwright tests
-        run: npx playwright test --output=playwright-report
+        run: npx playwright test
         env:
           CI: true
 
-      - name: List files in playwright-report before uploading to Xray
-        run: ls -l playwright-report
+      - name: Verify test results
+        run: |
+          if [ ! -f results.xml ]; then
+            echo "Error: Test results file not found!"
+            exit 1
+          fi
 
-      - name: Upload Playwright Report
+      - name: Upload Playwright JUnit Report
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
         with:
-          name: playwright-report
-          path: playwright-report/
+          name: playwright-junit-results
+          path: results.xml
           retention-days: 30
 
       - name: Get Xray API Token
@@ -67,10 +68,9 @@ jobs:
           TEST_EXECUTION_KEY=""  # default as empty string
 
           if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
-            # Making unique TEST_EXECUTION_KEY for для main_branch, base on commit SHA
             TEST_EXECUTION_KEY="MAIN-${GITHUB_SHA}"
-            
-            # Check if TEST_EXECUTION_KEY exist for main
+
+            # Create Test Execution if it doesn't exist
             CREATE_EXECUTION_RESPONSE=$(curl -s -X GET \
               -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
               -H "Content-Type: application/json" \
@@ -90,7 +90,6 @@ jobs:
                     }' \
                 "https://gfitn.atlassian.net/rest/api/2/issue")
 
-              # Отримуємо створений ключ Test Execution
               TEST_EXECUTION_KEY=$(echo "$RESPONSE" | jq -r '.key')
 
               if [[ "$TEST_EXECUTION_KEY" == "null" || -z "$TEST_EXECUTION_KEY" ]]; then
@@ -98,22 +97,19 @@ jobs:
                 echo "Response: $RESPONSE"
                 exit 1
               fi
-
               echo "New Test Execution created: $TEST_EXECUTION_KEY"
             else
               echo "Test Execution ${TEST_EXECUTION_KEY} already exists."
             fi
-
           elif [[ "${GITHUB_REF}" == "refs/heads/feature/"* ]] || [[ "${GITHUB_REF}" == "refs/heads/test/"* ]]; then
-            # Для feature і test гілок використовуємо стару логіку
             TEST_EXECUTION_KEY="DEV-${GITHUB_REF##*/}"
           fi
 
-          # Публікуємо результати тестів у Xray
+          # Upload test results
           curl -X POST \
             -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
             -H "Content-Type: multipart/form-data" \
-            -F "file=@playwright-report/test-results.xml" \
+            -F "file=@results.xml" \
             -F "projectKey=DEV" \
             -F "testExecutionKey=${TEST_EXECUTION_KEY}" \
             "https://gfitn.atlassian.net/api/v2/import/execution/junit" \
@@ -123,13 +119,10 @@ jobs:
         if: always()
         run: |
           STATUS="Success"
-          if [ ${{ steps.test.outcome }} != "success" ]; then
+          if [ ${{ steps.test.conclusion }} != "success" ]; then
             STATUS="Failed"
           fi
-          echo "Job URL: ${{ github.run_url }}"
-          echo "Job URL: ${{ github.event.workflow_run.url }}"
-
-          curl -X POST "https://api.telegram.org/bot7824475005:AAHMni_EljMyh3L8qKqXdafbetJD9gUxnkY/sendMessage" \
+          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
             -H "Content-Type: application/json" \
             -d '{
               "chat_id": "473468570",
