update playwright.yml

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -1,9 +1,10 @@
 name: Playwright Tests
 on:
   push:
-    branches: [main, master]
+    branches: [main, feature/**, test/**]
   pull_request:
-    branches: [main, master]
+    branches: [main, feature/**, test/**]
+
 jobs:
   test:
     timeout-minutes: 60
@@ -11,10 +12,12 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: lts/*
+
       - name: Cache Node.js modules
         uses: actions/cache@v3
         with:
@@ -22,14 +25,84 @@ jobs:
           key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-node-
+
       - name: Install dependencies
         run: npm ci
+
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
+
       - name: Run Playwright tests
-        run: npx playwright test
+        run: npx playwright test --reporter=junit --output=playwright-report
         env:
           CI: true
+
+      - name: Get Xray API Token
+        run: |
+          TOKEN=$(curl -s -X POST "https://xray.cloud.getxray.app/api/v2/authenticate" \
+            -H "Content-Type: application/json" \
+            -d '{
+                  "client_id": "${{ secrets.XRAY_CLIENT_ID }}",
+                  "client_secret": "${{ secrets.XRAY_CLIENT_SECRET }}"
+                }')
+          echo "Xray token: $TOKEN"
+          echo "XRAY_TOKEN=$TOKEN" >> $GITHUB_ENV
+
+      - name: Publish results to Xray
+        run: |
+          TEST_EXECUTION_KEY="DEV-112"  # default for main_branch
+          if [[ "${GITHUB_REF}" == "refs/heads/feature/"* ]]; then
+            # dynamic naming of execution as branch_name
+            TEST_EXECUTION_KEY="DEV-${GITHUB_REF##*/}"
+          elif [[ "${GITHUB_REF}" == "refs/heads/test/"* ]]; then
+            TEST_EXECUTION_KEY="DEV-${GITHUB_REF##*/}"  
+          fi
+
+          # Check if Test Execution exists in Xray
+          CREATE_EXECUTION_RESPONSE=$(curl -s -X GET \
+            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
+            -H "Content-Type: application/json" \
+            "https://gfitn.atlassian.net/rest/api/2/issue/${TEST_EXECUTION_KEY}")
+
+          # If Test Execution does not exist, create it
+          if echo "$CREATE_EXECUTION_RESPONSE" | grep -q '"errorMessages":'; then
+            echo "Test Execution ${TEST_EXECUTION_KEY} does not exist. Creating..."
+            RESPONSE=$(curl -s -X POST \
+              -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
+              -H "Content-Type: application/json" \
+              -d '{
+                    "fields": {
+                      "project": { "key": "DEV" },
+                      "summary": "Test Execution for '${GITHUB_REF##*/}'",
+                      "issuetype": { "name": "Test Execution" }
+                    }
+                  }' \
+              "https://gfitn.atlassian.net/rest/api/2/issue")
+
+            # Get created Test Execution key
+            TEST_EXECUTION_KEY=$(echo "$RESPONSE" | jq -r '.key')
+
+            # Check if Test Execution creation was successful
+            if [[ "$TEST_EXECUTION_KEY" == "null" || -z "$TEST_EXECUTION_KEY" ]]; then
+              echo "Error: Failed to create Test Execution."
+              echo "Response: $RESPONSE"
+              exit 1
+            fi
+
+            echo "New Test Execution created: $TEST_EXECUTION_KEY"
+          else
+            echo "Test Execution ${TEST_EXECUTION_KEY} already exists."
+          fi
+
+          # Publish results to Xray
+          curl -X POST \
+            -u ${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} \
+            -H "Content-Type: multipart/form-data" \
+            -F "file=@playwright-report/test-results.xml" \
+            -F "projectKey=DEV" \
+            -F "testExecutionKey=${TEST_EXECUTION_KEY}" \
+            "https://gfitn.atlassian.net/api/v2/import/execution/junit"
+
       - name: Send report to Telegram
         if: always()
         run: |
@@ -41,6 +114,7 @@ jobs:
           curl -X POST "https://api.telegram.org/bot7824475005:AAHMni_EljMyh3L8qKqXdafbetJD9gUxnkY/sendMessage" \
             -H "Content-Type: application/json" \
             -d '{"chat_id": "473468570", "text": "Playwright Tests: *'${STATUS}'*%0ARepository: '${{ github.repository }}'%0ABranch: '${{ github.ref_name }}'%0AJob URL: '${{ github.run_url }}'", "parse_mode": "Markdown"}'
+
       - name: Upload Playwright Report
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() }}
